server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        - id: inventory-service-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
